### ISSUE TITLE
Aliases for Slack

### ISSUE THREAD

**Issue by mmihir82** [StackStorm-Exchange/stackstorm-netbox#19]
Hi, Can you show example of aliases, If I want to ran thru slack channel and send to stackstorm. Below I tried creating the aliases, but seems not working. Can you suggest anything?
```
---
name: "nb_check_serial"
pack: "netbox"
action_ref: "netbox.get.dcim.devices"
description: "Netbox Search by Serial"
formats:
  - display: "netbox check serial <serial>"
    representation:
      - "{{ serial }}"
ack:
  format: "Executing - Device Serial: `{{execution.parameters.serial}}` ID: `{{ execution.id }}`"
  append_url: false
result:
  format: >
     *{{execution.parameters.serial}}*
     {% if execution.result.stderr -%}
     ```{{ execution.result.stderr }}```
     {%- else -%}```{{ execution.result.stdout }}``` {~}{~} {%- endif -%}
  ```
