### ISSUE TITLE
id parameter of get.dcim.devices action

### ISSUE THREAD

**Issue by rgrueebler** [StackStorm-Exchange/stackstorm-netbox#48]
Hi everyone,

I played around with the netbox.get.dcim.devices action. When I execute it without any parameters, it returns all the devices, which is expected. There is also the 'id' parameter. I assumed that I can get the data from a specific device with it. I realized that I need to enter a list. So I executed the action with an 'id' of '[1]'.

The return value of the action is this:
```
{
  "raw": {},
  "status": 404
}
```
In the nginx access logs from Netbox there is the following entry:
```
25/Feb/2024:08:15:33 -0500] "GET /api/dcim/devices/%5B1%5D/?save_in_key_store=False&save_in_key_store_ttl=60 HTTP/1.1" 404 23 "-" "python-requests/2.31.0"
```

My understanding is that '%5B1%5D/' represents '[1]'. So the action tries to access '/api/dcim/device/[1]...'.
Am I using the id parameter in the wrong way?

Thank you
Remo

**Comment by aopdal** [comment]
I think you are right, when I test creating a workflow using the action like this:
```
version: 1.0
tasks:
  task1:
    action: netbox.get.dcim.devices
    input:
      id:
        - 1
```
I get: 
`st2.actions.python.NetboxHTTPAction: DEBUG    endpoint_uri transformed to /dcim/devices/[1]/ because id was passed`

When I try in NetBox API /api/dcim/devices/{id}/ I get:

`/api/dcim/devices/1/`

And If I tries 

```
version: 1.0
tasks:
  # [261, 196]
  task1:
    action: netbox.get.dcim.devices
    input:
      id:
        - 1
        - 2
```
I get

`endpoint_uri transformed to /dcim/devices/[1, 2]/ because id was passed`

But I want something like:
`api/dcim/devices/?id=1&id=2`

So I think it looks like the action get.dcim.devices is a combination of two API endpoints:

/api/dcim/devices/
/api/dcim/devices/{id}/
