### ISSUE TITLE
post.dcim.interfaces dosn't allow untagged_vlan

### ISSUE THREAD

**Issue by rgrueebler** [StackStorm-Exchange/stackstorm-netbox#50]
Hi

I am using the following task:
```
add_interfaces_to_device:
    with:
      items: <% ctx(interfaces) %>
    action: netbox.post.dcim.interfaces
    input:
      device: <% str(ctx(device_id)) %>
      name: <% item().name %>
      type: '1000base-t'
      enabled: <% item().enabled %>
      description: <% item().description %>
      mode: access
      untagged_vlan: 10
```
When I run it without the 'utagged_vlan', it works. With this parameter I get a:
```
{
  "raw": {},
  "status": 404
}
```
Am I using the action wrong?

Thanks
Remo
