### ISSUE TITLE
netbox.get.ipam.prefixes.available_ips always gets 404s because of ID/url behavior in base action

### ISSUE THREAD

**Issue by danxg87** [StackStorm-Exchange/stackstorm-netbox#55]
Example issue:
```
st2 run netbox.get.ipam.prefixes.available_ips id=14162
id: 68333eeca62ad9d9e535f9c0
action.ref: netbox.get.ipam.prefixes.available_ips
context.user: dgeorge
parameters:
  id: 14162
status: succeeded
start_timestamp: Sun, 25 May 2025 16:01:48 UTC
end_timestamp: Sun, 25 May 2025 16:01:49 UTC
result:
  exit_code: 0
  result:
    raw: {}
    status: 404
  stderr: 'st2.actions.python.NetboxHTTPAction: DEBUG    endpoint_uri transformed to /ipam/prefixes/14162/available-ips/14162/ because id was passed
    st2.actions.python.NetboxHTTPAction: DEBUG    Calling base get to https://netbox-api.internal.digitalocean.com/api/ipam/prefixes/14162/available-ips/14162/ with kwargs: {''save_in_key_store_ttl'': 60, ''save_in_key_store_key_name'': None, ''save_in_key_store'': False}
    '
  stdout: '<Response [404]>
    '
```
(I've added stuff locally to print to stdout for debugging). This prefix+ID 100% exists, but note the URL is built here with the ID further APPENDED to the api path :( which, in this case, we aren't supposed to do???

I believe we may need to identify and add logic to handle the way the `endpoint_uri` is formed so we do not wind up breaking this functionality.

**Comment by danxg87** [comment]
It appears we HAVE a potential "skip appending ID to the endpoint URI" via
```
  get_detail_route_eligible:
    default: true
    immutable: true
    type: boolean
```
however, it's currently `immutable: true` so that prevents setting that value at runtime
